# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "All the Small Trips"
description: "People don't take trips, trips take people"

email: enicasoldo@gmail.com
#blog logo
logo: ""
float_logo: true # true, false (default)

# blog cover
cover: "assets/images/copertina-blog.jpg"

name: 'Enica Soldo'
author: 'Enica Soldo'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://allthesmalltrips.life"
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-87748609-2

# social icons and sharing options
social:
  - icon:	facebook-square
    url:	https://www.facebook.com/enica.soldo
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	instagram
    url:	https://www.instagram.com/enicasoldo/
    desc:	Follow me on Instagram
    share_url:
    share_title:
    share_link:
